export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  MANAGER: 'manager',
  RECEPTIONIST: 'receptionist',
  HOUSEKEEPING: 'housekeeping',
  CASHIER: 'cashier'
};

export const roleAccess = {
  home: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.RECEPTIONIST, ROLES.HOUSEKEEPING, ROLES.CASHIER],
  dashboard: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.RECEPTIONIST, ROLES.CASHIER],
  masterData: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  masterSettings: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  rooms: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  guests: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.RECEPTIONIST, ROLES.CASHIER],
  forecast: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.RECEPTIONIST],
  reservations: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.RECEPTIONIST],
  frontOffice: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.RECEPTIONIST, ROLES.CASHIER],
  checkInOut: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.RECEPTIONIST],
  billing: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.CASHIER, ROLES.RECEPTIONIST],
  housekeeping: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.HOUSEKEEPING],
  maintenance: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.HOUSEKEEPING],
  reports: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.CASHIER],
  pos: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.CASHIER],
  users: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  settings: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER]
};

export const canAccess = (role, feature) => roleAccess[feature]?.includes(role);
